services:
  db:
    container_name: typeorm-reloaded-db
    image: postgres:16.3
    ports:
      - 5432:5432
    env_file:
      - ./.env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - app-network
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always



networks:
  app-network:
    driver: bridge
  external: